---
services:

  sql-primary01:
    container_name: sql-primary01
    image: mariadb:11.4
    restart: unless-stopped
    volumes:
      - /srv/docker/sql-primary01:/var/lib/mysql
      - ./conf_primary1.cnf:/etc/mysql/conf.d/conf_primary.cnf
      - ./setup_replication_p1.sql:/docker-entrypoint-initdb.d/1.sql
    environment:
      - MARIADB_ROOT_PASSWORD=toto
      - MARIADB_DATABASE=wpd
      - MARIADB_USER=xav
      - MARIADB_PASSWORD=titi
      - MARIADB_REPLICATION_USER=replication_user
      - MARIADB_REPLICATION_PASSWORD=toto
    networks:
      - db-network

  sql-primary02:
    container_name: sql-primary02
    image: mariadb:11.4
    restart: unless-stopped
    volumes:
      - /srv/docker/sql-primary02:/var/lib/mysql
      - ./conf_primary2.cnf:/etc/mysql/conf.d/conf_primary.cnf
      - ./setup_replication_p2.sql:/docker-entrypoint-initdb.d/1.sql
    environment:
      - MARIADB_ROOT_PASSWORD=toto
      - MARIADB_DATABASE=wpd
      - MARIADB_USER=xav
      - MARIADB_PASSWORD=titi
      - MARIADB_REPLICATION_USER=replication_user
      - MARIADB_REPLICATION_PASSWORD=toto
    networks:
      - db-network

  wordpress:
    container_name: wp
    image: wordpress:6.6
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: sql-primary01:3306
      WORDPRESS_DB_USER: xav
      WORDPRESS_DB_PASSWORD: titi
      WORDPRESS_DB_NAME: wpd
    volumes:
      - /srv/docker/wordpress:/var/www/html
    networks:
      - db-network
      - front-network

volumes:
  shared-data:

networks:
  db-network:
  front-network:
